### ISSUE TITLE
Can I store data in GCS in avro format?

### ISSUE THREAD

**Issue by ee07dazn** [aiven/gcs-connector-for-apache-kafka#204]
Apologies in advance, for lack of understanding where exactly to post the question, I have submitted it in Issues. 

Basically, going through the docs, I can see data output formats as json, csv, parquet, with schema options in avro. I am keen to save data in avro format for efficiently loading into BQ. Is this currently possible or on roadmap soon?

Thanks in advance.

**Comment by ivanyu** [comment]
Hi @ee07dazn 
Unfortunately, the Avro output format is not supported yet. We can add it, though. I put it into our internal backlog.

**Comment by ee07dazn** [comment]
Thanks @ivanyu : would be super helpful if we can add it 🙌 as streaming directly in BQ is expensive (so used on case by case basis) and the most efficient uploading strategy with BQ is AVRO file format as per docs.

**Comment by ivanyu** [comment]
The connector now supports Parquet format, will it work? AFAIU, BigQuery [can load Parquet files](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet).

**Comment by ee07dazn** [comment]
@ivanyu : completely agree that BQ supports Parquet but we choose avro throughout the data project because of its efficiency compared to other formats. This has also been tested by various developers apart from the obvious recommendation from Google.

**Comment by ee07dazn** [comment]
Hi 👋 
Just curious to know if there is any ETA on this?
Thanks!

**Comment by ivanyu** [comment]
Hi
Unfortunately, no. We have it in our backlog, but we can't promise any date

**Comment by ee07dazn** [comment]
Hi 
Happy New Year!
Any update on this if possible ?

**Comment by aakarshg** [comment]
➕ 1 on this request. Our team is also quite interested in this feature.

**Comment by filip-yonov-aiven** [comment]
Hello, thank you for the posts! We will re-evaluate the priority given the demand and come back with estimates for making it available.

**Comment by jjaakola-aiven** [comment]
https://github.com/aiven/gcs-connector-for-apache-kafka/pull/267

In release https://github.com/aiven/gcs-connector-for-apache-kafka/releases/tag/v0.10.0
