### ISSUE TITLE
[Feature Request] Release Jar to Maven central repository

### ISSUE THREAD

**Issue by conorfennell** [aiven/gcs-connector-for-apache-kafka#77]
HI Aiven,

Firstly, thanks for the open-source connector.
As well as releasing on Github, I am requesting to release to Maven central repository?

**Comment by ivanyu** [comment]
Hi Conor,

This sounds like something we can technically do. However, could you please tell us more about your use case for this? Connectors are rarely added as dependencies to projects via Maven or other build systems.

**Comment by conorfennell** [comment]
As part of our CI, we are embedding Jars in the Confluent Kafka Connect docker image.
The other connectors we use are available through a maven repository.

With the maven repository, the Dockerfile has these steps
1. Use gradle|mvn|sbt to pull any required connector Jars
2. Copy Jars to plugins path

Without:
1. Use gradle|mvn|sbt to pull any required connector Jars
2. Copy Jars to plugins path
3. Curl Aiven connector tar | unzip tar | plugin path

Also, one useful thing for companies is typically maven repositories are proxied, and it would leverage the vulnerability scanning for bringing in external Jars.

**Comment by conorfennell** [comment]
Just an example of how neat it is.

`build.gradle.kts`
```kotlin
val connectors = configurations.create("kafkaConnectDependencies")
dependencies {
    connectors("'io.debezium:debezium-connector-postgres:1.3.1.Final")
    connectors("'io.debezium:debezium-connector-mongodb:1.3.1.Final")
    connectors("com.aiven:gcs-sink-connector:1.14.0")
}

tasks.register<Copy>("downloadConnectors") {
    from(connectors)
    into("connectors")
}
```

`Dockerfile`
```dockerfile
ARG CP_KAFKA_CONNECT_VERSION=5.5.2
FROM hub.docker.prod.walmart.com/library/gradle:6.4.0-jdk11 AS build
WORKDIR /app
COPY . /app/
RUN gradle downloadConnectors

FROM hub.docker.prod.walmart.com/confluentinc/cp-kafka-connect:${CP_KAFKA_CONNECT_VERSION}
RUN adduser --system --uid 10000 --group --shell /sbin/nologin --home /opt/app/ app

COPY --from=build /app/connectors/*  /usr/share/java/

ENTRYPOINT exec /usr/bin/connect-distributed /app/connect-distributed.properties
```

**Comment by ivanyu** [comment]
The use case is very clear and we definitely should do this.
Will it make much difference for you if we won't use Maven central, but our Bintray repo? You'll just need to add something like
```groovy
repositories {
    maven {
        url "http://dl.bintray.com/aiven/maven"
    }
}
```

**Comment by drinkbird** [comment]
Hey Ivan, same issue here, and Maven central would be more convenient due to internal restrictions

**Comment by ivanyu** [comment]
Thank you for your interest, @drinkbird.
Could you answer the same question ⬆️: will Bintray work for you?

**Comment by ivanyu** [comment]
Thank you for your interest @drinkbird. Maven Central it will be.
We will be working on this and publish updates to this issue.

**Comment by ivanyu** [comment]
Just published the latest version to Maven Central: https://repo1.maven.org/maven2/io/aiven/aiven-kafka-connect-gcs/0.6.1/

**Comment by drinkbird** [comment]
Many thanks Ivan!

**Comment by conorfennell** [comment]
Thank @ivanyu!
This can be closed now.

**Comment by ivanyu** [comment]
No worries, I'll keep it for some time while we're adding this into the CI.
